# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joe < Formula
  desc "Generate command lines based on Joe-cli"
  homepage "https://github.com/Carbonfrost/joe-cli"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.3.1/joe-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "f908ac4d001f23d0e775ea51b333b242b51fc350455cba7bd5ca88cd31f92434"

      def install
        bin.install "joe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.3.1/joe-cli_0.3.1_darwin_x86_64.tar.gz"
      sha256 "6389657546810251783e9f035570bff57900b8a84cc7b96b820992cf70cad9a3"

      def install
        bin.install "joe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.3.1/joe-cli_0.3.1_linux_x86_64.tar.gz"
      sha256 "32ac3f9a31fa4368547789e9f29231093efa3cbe81d42f3abf98511804c1b947"

      def install
        bin.install "joe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.3.1/joe-cli_0.3.1_linux_arm64.tar.gz"
      sha256 "05f55f9edc6ccfecdffb05fae5392127dd444d69abc9eebfab4e9be547031a5c"

      def install
        bin.install "joe"
      end
    end
  end
end
