# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Joe < Formula
  desc "Generate command lines based on Joe-cli"
  homepage "https://github.com/Carbonfrost/joe-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.5.0/joe-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "5c545afdda2c80bc44f518c2923a5b5670bb23117626ec8ca6b53194b72af7c8"

      def install
        bin.install "joe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.5.0/joe-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "833a4089ea7077c9df08d5deed6004343fb8980f728884f0327e8138426c1236"

      def install
        bin.install "joe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.5.0/joe-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "fe2b1c474a2ba887eeca1f9299d50ebc2c9f942f0ca0d899416f2784689092f8"

      def install
        bin.install "joe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli/releases/download/v0.5.0/joe-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "d1a53b977b9f02ba0c59a008a827423329cb61c8d9389cbbc1b3c8e60062509b"

      def install
        bin.install "joe"
      end
    end
  end
end
