# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mechanic < Formula
  desc "Markdown processing and rendering"
  homepage "https://github.com/Carbonfrost/mechanic"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/mechanic/releases/download/v0.1.0/mechanic_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba16edfd0bf8f78ae76fd6924166b0ab601e4b4316e073ea37274837a1a70b55"

      def install
        bin.install "mechanic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/mechanic/releases/download/v0.1.0/mechanic_0.1.0_darwin_amd64.tar.gz"
      sha256 "75573c7579c9f7c5d1b3cc7b67e49f2fcab49418fc74399b5a7f28adb080f49c"

      def install
        bin.install "mechanic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/mechanic/releases/download/v0.1.0/mechanic_0.1.0_linux_arm64.tar.gz"
      sha256 "95cb6b0264ef09f5816fcf70bb730cdcd22011c731bc159636cc0324d6973c45"

      def install
        bin.install "mechanic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/mechanic/releases/download/v0.1.0/mechanic_0.1.0_linux_amd64.tar.gz"
      sha256 "e8cd90db4446dc9e404f71643608a714dd42b651a2fdce548c82ab05a791e960"

      def install
        bin.install "mechanic"
      end
    end
  end
end
