# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pastiche < Formula
  desc "Make requests to HTTP APIs using their OpenAPI schemas and definitions"
  homepage "https://github.com/Carbonfrost/pastiche"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/pastiche/releases/download/v0.1.0/pastiche_0.1.0_darwin_x86_64.tar.gz"
      sha256 "15ecbe83cbfa87fdebc54842b2e51cbcea685e080c1a71be6814fec1a075a47d"

      def install
        bin.install "pastiche"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/pastiche/releases/download/v0.1.0/pastiche_0.1.0_darwin_arm64.tar.gz"
      sha256 "e728bf6083658719d2b274e76fd249a2f3488e4fb496e18a91f468852e926de8"

      def install
        bin.install "pastiche"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/pastiche/releases/download/v0.1.0/pastiche_0.1.0_linux_arm64.tar.gz"
      sha256 "706fabfdeae9a97fcbaad169ed41d6599210bca02bfc732c594ba1f37a1635f3"

      def install
        bin.install "pastiche"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/pastiche/releases/download/v0.1.0/pastiche_0.1.0_linux_x86_64.tar.gz"
      sha256 "0a20d7e681f871e7e74e861b518790bcc3e0bd265d2a653be7c636d1b3808bff"

      def install
        bin.install "pastiche"
      end
    end
  end
end
