# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toupee < Formula
  desc "Expands RFC 6570 (level 4) URI templates"
  homepage "https://github.com/Carbonfrost/joe-cli-http"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/toupee_0.2.0_darwin_x86_64.tar.gz"
      sha256 "d22735d67c7fa4d79c5f2a9551ce8d47094badf982617a24983be6ade98e34be"

      def install
        bin.install "toupee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/toupee_0.2.0_darwin_arm64.tar.gz"
      sha256 "26a9db8e5bf6368513c85e0c93fa1b165d1417b729212bc07c53638248e50593"

      def install
        bin.install "toupee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/toupee_0.2.0_linux_x86_64.tar.gz"
      sha256 "b5f2f5f4af6164b1b18f9e6c2ebd777c324c0c9c626b4d4d5460d312317c6e8a"

      def install
        bin.install "toupee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/toupee_0.2.0_linux_arm64.tar.gz"
      sha256 "663d5bfc49885fc382210a177072b4cfc26ce23a0369b32897cea00e2a630893"

      def install
        bin.install "toupee"
      end
    end
  end
end
