# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toupee < Formula
  desc "Expands RFC 6570 (level 4) URI templates"
  homepage "https://github.com/Carbonfrost/joe-cli-http"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.5.0/toupee_0.5.0_darwin_amd64.tar.gz"
      sha256 "f30ea9d1e2f01c5dc07c7e6a2d97c778493ea12bbd055cad7aff263a8bf01506"

      def install
        bin.install "toupee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.5.0/toupee_0.5.0_darwin_arm64.tar.gz"
      sha256 "30d41b198c5e8f2075462aecf6c3de3260d1bdde4884684beeb49ef159c1ffd9"

      def install
        bin.install "toupee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.5.0/toupee_0.5.0_linux_arm64.tar.gz"
      sha256 "2261793ff369bd8912213192c3fd8b9330049d6560421da66c0d46e3de722edc"

      def install
        bin.install "toupee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.5.0/toupee_0.5.0_linux_amd64.tar.gz"
      sha256 "17c147b96dc39a7ee32fc588d0098f65e25e35b8c24f4d545691cae2bdbceede"

      def install
        bin.install "toupee"
      end
    end
  end
end
