# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wig < Formula
  desc "Provides access to the Go HTTP client with some cURL compatibility"
  homepage "https://github.com/Carbonfrost/joe-cli-http"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/wig_0.2.0_darwin_x86_64.tar.gz"
      sha256 "922bd7babedbe74f09a3fb789fd5533b4ebf14423f144350ac1177124ccb667f"

      def install
        bin.install "wig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/wig_0.2.0_darwin_arm64.tar.gz"
      sha256 "93dca930add7dec07dd1829fd214252b2709bfe1955360007734e252c8d9c9dc"

      def install
        bin.install "wig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/wig_0.2.0_linux_x86_64.tar.gz"
      sha256 "6b7ff2de0f7db9fc53b5395fb669d8c983bed18f7a333401170d8cc8123e8081"

      def install
        bin.install "wig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Carbonfrost/joe-cli-http/releases/download/v0.2.0/wig_0.2.0_linux_arm64.tar.gz"
      sha256 "c2327a43904cabd826a61496fd15afe3e84a777bc09f0cbe81558207893cef2b"

      def install
        bin.install "wig"
      end
    end
  end
end
